services:
  postgres:
     image: postgres:17
     container_name: gospoc-postgres
     environment:
        POSTGRES_DB: judge
        POSTGRES_USER: judge
        POSTGRES_PASSWORD: judge
     ports:
        - "5432:5432"
     volumes:
        - postgres_data:/var/lib/postgresql/data 
  redis:
    image: redis:8.8.0
    container_name: gospoc-redis
    ports:
      - "6380:6379"

volumes:
  postgres_data: